### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by Jazz-SM** [omnicomtech/alphaprint#1]
Add the option for the user to get no hex or other feedback during the program and simply get a confirmation at the end. This will be accomplished by adding the optional argument "-v" to the end of the input. So for no information the program is called as such: AlphaPrint.py x x x x -v. If the user still wants all the text, it is called as such AlphaPrint.py x x x x.

**Comment by colinpbarry** [comment]
Let's either use -v for displaying the extended hex information or -q to hide it
